- markdown: |
    ## Rockstar alert
    Thanks for this contribution, we _really_ appreciate your help :heart:!

- markdown: |
    ## Uh oh
    Don't check in binaries...we use GitHub Packages for those!
  blocking: true
  pathFilter:
    - '+**/*.dll'

- markdown: |
    Are you _sure_ you want to be console logging or debuggering here?? :trollface:
  blocking: true
  pathFilter:
    - 'src/**'
  contentFilter:
    - '(\+\s*console.log\(.*\))'
    - '(\+\s*debugger)'