name: PR Review
on:
  pull_request:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: nitpicker
        uses: ethanis/nitpicker@v1
        with:
          nitpicks: '/.github/nitpicks.yml'
          token: '${{ secrets.GITHUB_TOKEN }}'