name: PR Review
on:
  pull_request:
  push:
    branches:
      - develop
jobs:
  pr-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: nitpicker
        uses: ethanis/nitpicker
        with:
          nitpicks: '.github/nitpicks.yml'
          token: '${{ secrets.GITHUB_TOKEN }}'